apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment-mutant
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers: 
      - name: node
        image: stenionljunior/node:latest
        ports:
        - containerPort: 3000
