name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: hadolint
      uses: reviewdog/action-hadolint@v1
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the latest Docker image
      run: docker build app/ --file Dockerfile --tag stenionljunior/node:latest
    - name: Push the latest Docker image
      run: docker push stenionljunior/node:latest
